# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=45)),
                ('make', models.CharField(max_length=45)),
				('model year', models.CharField(max_length=45)),
				('plate number', models.CharField(max_length=45)),
				('color', models.CharField(max_length=45)),
            ],
        ),
		
		migrations.CreateModel(
            name='Living',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=45)),
                ('district', models.CharField(max_length=45)),
				('house type', models.CharField(max_length=45)),
				('heating', models.CharField(max_length=45)),
				('avg monthly cost', models.CharField(max_length=45)),
            ],
        ),
]
