# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model year',
            new_name='plate',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='plate number',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='living',
            old_name='avg monthly cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='living',
            old_name='house type',
            new_name='house',
        ),
    ]
